name: Renovate

on:
  # Schedule: run every day at 2am
  schedule:
    - cron: '0 2 * * *'
  
  # Run on demand via workflow_dispatch
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Renovate log level'
        required: true
        default: 'info'
        type: choice
        options:
          - debug
          - info
          - warn
          - error
      dryRun:
        description: 'Dry run'
        type: boolean
        default: false

# Prevent multiple Renovate runs from happening simultaneously
concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    
    # Allow renovate to create PRs
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Use custom docker-based renovate to run self-hosted
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.0.4
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          DRY_RUN: ${{ inputs.dryRun == true && 'full' || '' }}
          RENOVATE_BASE_BRANCHES: 'main'
          RENOVATE_EXTENDS: 'config:recommended,group:allNonMajor'
          # Include local configuration files
          RENOVATE_CONFIG_FILE: 'renovate.json5'
          RENOVATE_EXTENDS_FROM: |
            .github/renovate-automerge.json5
            .github/renovate-groups.json5